name: Front-End Build & Testing

on:
  push:
    branches: [ "master" ]
    paths:
      - 'diversitytracker.web/**'
      - 'diversitytracker.web.tests/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'diversitytracker.web/**'
      - 'diversitytracker.web.tests/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Change to Root Directory
      run: cd ${{ github.workspace }}

    - name: List directories
      run: ls -lah

    - name: Install dependencies (Web)
      working-directory: ./diversitytracker.web
      run: npm ci

    - name: Build (Web)
      working-directory: ./diversitytracker.web
      run: npm run build --if-present

    - name: Install dependencies (Tests)
      working-directory: ./diversitytracker.web.tests
      run: npm ci

    - name: Run tests (Tests)
      working-directory: ./diversitytracker.web.tests
      run: npm test
